.TH "QCommandLineConfigEntry" 3 "Sun Oct 16 2011" "Version 0.3.0" "QCommandLine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCommandLineConfigEntry \- 
.PP
Configuration entry structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qcommandline.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQCommandLine::Type\fP \fBtype\fP"
.br
.ti -1c
.RI "QChar \fBshortName\fP"
.br
.ti -1c
.RI "QString \fBlongName\fP"
.br
.ti -1c
.RI "QString \fBdescr\fP"
.br
.ti -1c
.RI "\fBQCommandLine::Flags\fP \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration entry structure. 
.PP
Definition at line 360 of file qcommandline.h.
.SH "Member Data Documentation"
.PP 
.SS "QString \fBQCommandLineConfigEntry::descr\fP"Description, used in --help 
.PP
Definition at line 376 of file qcommandline.h.
.SS "\fBQCommandLine::Flags\fP \fBQCommandLineConfigEntry::flags\fP"Option flags 
.PP
Definition at line 380 of file qcommandline.h.
.SS "QString \fBQCommandLineConfigEntry::longName\fP"Long Name 
.PP
Definition at line 372 of file qcommandline.h.
.SS "QChar \fBQCommandLineConfigEntry::shortName\fP"Short Name 
.PP
Definition at line 368 of file qcommandline.h.
.SS "\fBQCommandLine::Type\fP \fBQCommandLineConfigEntry::type\fP"Entry Type 
.PP
Definition at line 364 of file qcommandline.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for QCommandLine from the source code.
