.TH "QCommandLinePrivate" 3 "Wed Apr 20 2011" "Version 0.2.0" "QCommandLine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCommandLinePrivate \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBversion\fP"
.br
.ti -1c
.RI "bool \fBhelp\fP"
.br
.ti -1c
.RI "QStringList \fBargs\fP"
.br
.ti -1c
.RI "QCommandLineConfig \fBconfig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file qcommandline.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for QCommandLine from the source code.
