.TH "QCommandLineConfigEntry" 3 "Wed Apr 20 2011" "Version 0.2.0" "QCommandLine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QCommandLineConfigEntry \- 
.PP
Configuration entry structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qcommandline.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQCommandLine::Type\fP \fBtype\fP"
.br
.ti -1c
.RI "QChar \fBshortName\fP"
.br
.ti -1c
.RI "QString \fBlongName\fP"
.br
.ti -1c
.RI "QString \fBdescr\fP"
.br
.ti -1c
.RI "\fBQCommandLine::Flags\fP \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration entry structure. 
.PP
Definition at line 335 of file qcommandline.h.
.SH "Member Data Documentation"
.PP 
.SS "QString \fBQCommandLineConfigEntry::descr\fP"Description, used in --help 
.PP
Definition at line 351 of file qcommandline.h.
.SS "\fBQCommandLine::Flags\fP \fBQCommandLineConfigEntry::flags\fP"Option flags 
.PP
Definition at line 355 of file qcommandline.h.
.SS "QString \fBQCommandLineConfigEntry::longName\fP"Long Name 
.PP
Definition at line 347 of file qcommandline.h.
.SS "QChar \fBQCommandLineConfigEntry::shortName\fP"Short Name 
.PP
Definition at line 343 of file qcommandline.h.
.SS "\fBQCommandLine::Type\fP \fBQCommandLineConfigEntry::type\fP"Entry Type 
.PP
Definition at line 339 of file qcommandline.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for QCommandLine from the source code.
